# -*- coding: utf-8 -*-
"""news.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EI6EH-_xdfbOp9ixGupUtimKvjfEm0i4
"""

!pip install pygooglenews

#Ex6. Modular Programming: Scrap news from Hacker News
from google.colab import files
uploaded = files.upload()

import news as n
df1=n.scrap_news("hacker news")
display(df1)

import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS
wordcloud = WordCloud(background_color="white",width=1600, height=800).generate(''.join(df1['title'].tolist()))
plt.figure( figsize=(12,10), facecolor='k')
plt.imshow(wordcloud)

!pip install scapy

#Ex7.Banner Grabbing Scapy
import socket
import requests
from scapy.all import sniff
#getting ip of domain
hostname = input("Enter the website url (full)")
ip= socket.gethostbyname(hostname)
print(hostname,"\n",ip)
#Banner grabbing
def banner(ip, port):
    s = socket.socket()
    s.connect((ip, int(port)))
    print(s.recv(1024))
port = str(input("Please enter the port: "))
banner(ip, port)
print(hostname)
#check if vulnerable
domain = "https://www."+hostname
headers= requests.get(domain).headers

if 'X-Frame-Options' in headers:
    print(domain," non - vulnerable")
else:
    print(domain, " vulnerable")